/**
 * Portuguese Flashcard Data
 * Embedded vocabulary data - 460 words total
 */

const FUNCTION_WORDS = [
  {"pt": "eu", "en": "I", "type": "pronoun", "example_pt": "Eu sou brasileiro.", "example_en": "I am Brazilian."},
  {"pt": "você", "en": "you", "type": "pronoun", "example_pt": "De onde você é?", "example_en": "Where are you from?"},
  {"pt": "ele", "en": "he", "type": "pronoun", "example_pt": "Ele é americano.", "example_en": "He is American."},
  {"pt": "ela", "en": "she", "type": "pronoun", "example_pt": "Ela é brasileira.", "example_en": "She is Brazilian."},
  {"pt": "nós", "en": "we", "type": "pronoun", "example_pt": "Nós somos amigos.", "example_en": "We are friends."},
  {"pt": "eles", "en": "they (masc.)", "type": "pronoun", "example_pt": "Eles estão felizes.", "example_en": "They are happy."},
  {"pt": "elas", "en": "they (fem.)", "type": "pronoun", "example_pt": "Elas são professoras.", "example_en": "They are teachers."},
  {"pt": "a gente", "en": "we (informal)", "type": "pronoun", "example_pt": "A gente vai ao cinema.", "example_en": "We're going to the movies."},
  {"pt": "o", "en": "the (masc. sing.)", "type": "article", "example_pt": "O livro está na mesa.", "example_en": "The book is on the table."},
  {"pt": "a", "en": "the (fem. sing.)", "type": "article", "example_pt": "A caneta é azul.", "example_en": "The pen is blue."},
  {"pt": "os", "en": "the (masc. pl.)", "type": "article", "example_pt": "Os carros são rápidos.", "example_en": "The cars are fast."},
  {"pt": "as", "en": "the (fem. pl.)", "type": "article", "example_pt": "As casas são grandes.", "example_en": "The houses are big."},
  {"pt": "um", "en": "a/an (masc.)", "type": "article", "example_pt": "Comprei um sapato novo.", "example_en": "I bought a new shoe."},
  {"pt": "uma", "en": "a/an (fem.)", "type": "article", "example_pt": "Comprei uma blusa nova.", "example_en": "I bought a new blouse."},
  {"pt": "uns", "en": "some (masc. pl.)", "type": "article", "example_pt": "Uns amigos vieram visitar.", "example_en": "Some friends came to visit."},
  {"pt": "umas", "en": "some (fem. pl.)", "type": "article", "example_pt": "Umas meninas estão lá fora.", "example_en": "Some girls are outside."},
  {"pt": "de", "en": "of/from", "type": "preposition", "example_pt": "Eu sou de São Paulo.", "example_en": "I am from São Paulo."},
  {"pt": "em", "en": "in/on/at", "type": "preposition", "example_pt": "Eu moro em Nova Iorque.", "example_en": "I live in New York."},
  {"pt": "para", "en": "to/for", "type": "preposition", "example_pt": "Eu vou para o Brasil.", "example_en": "I'm going to Brazil."},
  {"pt": "por", "en": "by/through/per", "type": "preposition", "example_pt": "Vou enviar por e-mail.", "example_en": "I'll send it by email."},
  {"pt": "com", "en": "with", "type": "preposition", "example_pt": "Eu falo com meus amigos.", "example_en": "I talk with my friends."},
  {"pt": "sem", "en": "without", "type": "preposition", "example_pt": "Não vivo sem música.", "example_en": "I can't live without music."},
  {"pt": "entre", "en": "between/among", "type": "preposition", "example_pt": "O livro está entre os dois.", "example_en": "The book is between the two."},
  {"pt": "sobre", "en": "about/on", "type": "preposition", "example_pt": "Falamos sobre o filme.", "example_en": "We talked about the movie."},
  {"pt": "até", "en": "until/up to", "type": "preposition", "example_pt": "Trabalho até as seis.", "example_en": "I work until six."},
  {"pt": "desde", "en": "since/from", "type": "preposition", "example_pt": "Moro aqui desde 2020.", "example_en": "I've lived here since 2020."},
  {"pt": "e", "en": "and", "type": "conjunction", "example_pt": "Eu trouxe caderno e caneta.", "example_en": "I brought notebook and pen."},
  {"pt": "mas", "en": "but", "type": "conjunction", "example_pt": "O carro é velho, mas funciona.", "example_en": "The car is old but it works."},
  {"pt": "ou", "en": "or", "type": "conjunction", "example_pt": "Você quer chá ou café?", "example_en": "Do you want tea or coffee?"},
  {"pt": "porque", "en": "because", "type": "conjunction", "example_pt": "Estudei porque quero passar.", "example_en": "I studied because I want to pass."},
  {"pt": "quando", "en": "when", "type": "conjunction", "example_pt": "Ligue quando chegar.", "example_en": "Call when you arrive."},
  {"pt": "se", "en": "if", "type": "conjunction", "example_pt": "Se chover, não vou.", "example_en": "If it rains, I won't go."},
  {"pt": "que", "en": "that/which", "type": "conjunction", "example_pt": "O livro que comprei é bom.", "example_en": "The book that I bought is good."},
  {"pt": "como", "en": "how/as", "type": "conjunction", "example_pt": "Como você está?", "example_en": "How are you?"},
  {"pt": "enquanto", "en": "while", "type": "conjunction", "example_pt": "Durma enquanto pode.", "example_en": "Sleep while you can."},
  {"pt": "este", "en": "this (masc.)", "type": "demonstrative", "example_pt": "Este computador é novo.", "example_en": "This computer is new."},
  {"pt": "esta", "en": "this (fem.)", "type": "demonstrative", "example_pt": "Esta blusa é bonita.", "example_en": "This blouse is pretty."},
  {"pt": "esse", "en": "that (masc.)", "type": "demonstrative", "example_pt": "Esse carro é rápido.", "example_en": "That car is fast."},
  {"pt": "essa", "en": "that (fem.)", "type": "demonstrative", "example_pt": "Essa casa é grande.", "example_en": "That house is big."},
  {"pt": "aquele", "en": "that over there (masc.)", "type": "demonstrative", "example_pt": "Aquele homem é alto.", "example_en": "That man over there is tall."},
  {"pt": "aquela", "en": "that over there (fem.)", "type": "demonstrative", "example_pt": "Aquela mulher é médica.", "example_en": "That woman over there is a doctor."},
  {"pt": "quem", "en": "who", "type": "question_word", "example_pt": "Quem é você?", "example_en": "Who are you?"},
  {"pt": "que", "en": "what", "type": "question_word", "example_pt": "Que horas são?", "example_en": "What time is it?"},
  {"pt": "qual", "en": "which", "type": "question_word", "example_pt": "Qual é o seu nome?", "example_en": "Which is your name?"},
  {"pt": "onde", "en": "where", "type": "question_word", "example_pt": "Onde você mora?", "example_en": "Where do you live?"},
  {"pt": "quando", "en": "when", "type": "question_word", "example_pt": "Quando você chega?", "example_en": "When do you arrive?"},
  {"pt": "como", "en": "how", "type": "question_word", "example_pt": "Como você vai?", "example_en": "How are you going?"},
  {"pt": "por que", "en": "why", "type": "question_word", "example_pt": "Por que você foi?", "example_en": "Why did you go?"},
  {"pt": "quanto", "en": "how much", "type": "question_word", "example_pt": "Quanto custa isso?", "example_en": "How much does this cost?"},
  {"pt": "não", "en": "no/not", "type": "adverb", "example_pt": "Eu não sei tocar piano.", "example_en": "I don't know how to play piano."},
  {"pt": "sim", "en": "yes", "type": "adverb", "example_pt": "Ela disse sim ao convite.", "example_en": "She said yes to the invitation."},
  {"pt": "muito", "en": "very/many", "type": "adverb", "example_pt": "O Brasil é muito grande.", "example_en": "Brazil is very big."},
  {"pt": "mais", "en": "more", "type": "adverb", "example_pt": "Ele é mais alto que ela.", "example_en": "He is taller than her."},
  {"pt": "menos", "en": "less", "type": "adverb", "example_pt": "Eu deveria comer menos doce.", "example_en": "I should eat less sweets."},
  {"pt": "já", "en": "already/now", "type": "adverb", "example_pt": "Eu já terminei o trabalho.", "example_en": "I already finished the work."},
  {"pt": "ainda", "en": "still", "type": "adverb", "example_pt": "Você ainda está aqui?", "example_en": "Are you still here?"},
  {"pt": "também", "en": "also/too", "type": "adverb", "example_pt": "Meu marido também é brasileiro.", "example_en": "My husband is also Brazilian."},
  {"pt": "só", "en": "only/just", "type": "adverb", "example_pt": "Tenho só cinco reais.", "example_en": "I have only five reais."},
  {"pt": "bem", "en": "well", "type": "adverb", "example_pt": "Ela canta muito bem.", "example_en": "She sings very well."},
  {"pt": "mal", "en": "badly", "type": "adverb", "example_pt": "Ele dormiu mal ontem.", "example_en": "He slept badly yesterday."}
];

const CONTENT_WORDS = [
  {"pt": "fazer", "en": "to do/make", "type": "verb", "rank": 1},
  {"pt": "ser", "en": "to be (permanent)", "type": "verb", "rank": 2},
  {"pt": "ter", "en": "to have", "type": "verb", "rank": 3},
  {"pt": "estar", "en": "to be (temporary)", "type": "verb", "rank": 4},
  {"pt": "ir", "en": "to go", "type": "verb", "rank": 5},
  {"pt": "dizer", "en": "to say/tell", "type": "verb", "rank": 6},
  {"pt": "ver", "en": "to see", "type": "verb", "rank": 7},
  {"pt": "dar", "en": "to give", "type": "verb", "rank": 8},
  {"pt": "vir", "en": "to come", "type": "verb", "rank": 9},
  {"pt": "querer", "en": "to want", "type": "verb", "rank": 10},
  {"pt": "poder", "en": "to be able to/can", "type": "verb", "rank": 11},
  {"pt": "falar", "en": "to speak/talk", "type": "verb", "rank": 12},
  {"pt": "ficar", "en": "to stay/become", "type": "verb", "rank": 13},
  {"pt": "ouvir", "en": "to hear/listen", "type": "verb", "rank": 14},
  {"pt": "achar", "en": "to think/find", "type": "verb", "rank": 15},
  {"pt": "sair", "en": "to go out/leave", "type": "verb", "rank": 16},
  {"pt": "chegar", "en": "to arrive", "type": "verb", "rank": 17},
  {"pt": "passar", "en": "to pass/spend", "type": "verb", "rank": 18},
  {"pt": "pedir", "en": "to ask for/order", "type": "verb", "rank": 19},
  {"pt": "saber", "en": "to know", "type": "verb", "rank": 20},
  {"pt": "gostar", "en": "to like", "type": "verb", "rank": 21},
  {"pt": "conhecer", "en": "to know/meet", "type": "verb", "rank": 22},
  {"pt": "precisar", "en": "to need", "type": "verb", "rank": 23},
  {"pt": "deixar", "en": "to let/leave", "type": "verb", "rank": 24},
  {"pt": "levar", "en": "to take/carry", "type": "verb", "rank": 25},
  {"pt": "trazer", "en": "to bring", "type": "verb", "rank": 26},
  {"pt": "pegar", "en": "to grab/take", "type": "verb", "rank": 27},
  {"pt": "pensar", "en": "to think", "type": "verb", "rank": 28},
  {"pt": "contar", "en": "to tell/count", "type": "verb", "rank": 29},
  {"pt": "entrar", "en": "to enter", "type": "verb", "rank": 30},
  {"pt": "encontrar", "en": "to find/meet", "type": "verb", "rank": 31},
  {"pt": "trabalhar", "en": "to work", "type": "verb", "rank": 32},
  {"pt": "comer", "en": "to eat", "type": "verb", "rank": 33},
  {"pt": "dormir", "en": "to sleep", "type": "verb", "rank": 34},
  {"pt": "beber", "en": "to drink", "type": "verb", "rank": 35},
  {"pt": "comprar", "en": "to buy", "type": "verb", "rank": 36},
  {"pt": "pagar", "en": "to pay", "type": "verb", "rank": 37},
  {"pt": "morrer", "en": "to die", "type": "verb", "rank": 38},
  {"pt": "matar", "en": "to kill", "type": "verb", "rank": 39},
  {"pt": "viver", "en": "to live", "type": "verb", "rank": 40},
  {"pt": "parar", "en": "to stop", "type": "verb", "rank": 41},
  {"pt": "começar", "en": "to start/begin", "type": "verb", "rank": 42},
  {"pt": "terminar", "en": "to finish/end", "type": "verb", "rank": 43},
  {"pt": "continuar", "en": "to continue", "type": "verb", "rank": 44},
  {"pt": "acabar", "en": "to finish/end", "type": "verb", "rank": 45},
  {"pt": "tentar", "en": "to try", "type": "verb", "rank": 46},
  {"pt": "esperar", "en": "to wait/hope", "type": "verb", "rank": 47},
  {"pt": "procurar", "en": "to look for", "type": "verb", "rank": 48},
  {"pt": "ajudar", "en": "to help", "type": "verb", "rank": 49},
  {"pt": "ganhar", "en": "to win/earn", "type": "verb", "rank": 50},
  {"pt": "perder", "en": "to lose", "type": "verb", "rank": 51},
  {"pt": "amar", "en": "to love", "type": "verb", "rank": 52},
  {"pt": "sentir", "en": "to feel", "type": "verb", "rank": 53},
  {"pt": "lembrar", "en": "to remember", "type": "verb", "rank": 54},
  {"pt": "esquecer", "en": "to forget", "type": "verb", "rank": 55},
  {"pt": "entender", "en": "to understand", "type": "verb", "rank": 56},
  {"pt": "aprender", "en": "to learn", "type": "verb", "rank": 57},
  {"pt": "ensinar", "en": "to teach", "type": "verb", "rank": 58},
  {"pt": "estudar", "en": "to study", "type": "verb", "rank": 59},
  {"pt": "ler", "en": "to read", "type": "verb", "rank": 60},
  {"pt": "escrever", "en": "to write", "type": "verb", "rank": 61},
  {"pt": "correr", "en": "to run", "type": "verb", "rank": 62},
  {"pt": "andar", "en": "to walk", "type": "verb", "rank": 63},
  {"pt": "dirigir", "en": "to drive", "type": "verb", "rank": 64},
  {"pt": "tocar", "en": "to touch/play (instrument)", "type": "verb", "rank": 65},
  {"pt": "cantar", "en": "to sing", "type": "verb", "rank": 66},
  {"pt": "dançar", "en": "to dance", "type": "verb", "rank": 67},
  {"pt": "jogar", "en": "to play/throw", "type": "verb", "rank": 68},
  {"pt": "brincar", "en": "to play (children)", "type": "verb", "rank": 69},
  {"pt": "usar", "en": "to use/wear", "type": "verb", "rank": 70},
  {"pt": "vestir", "en": "to dress", "type": "verb", "rank": 71},
  {"pt": "abrir", "en": "to open", "type": "verb", "rank": 72},
  {"pt": "fechar", "en": "to close", "type": "verb", "rank": 73},
  {"pt": "ligar", "en": "to call/turn on", "type": "verb", "rank": 74},
  {"pt": "desligar", "en": "to turn off", "type": "verb", "rank": 75},
  {"pt": "mudar", "en": "to change", "type": "verb", "rank": 76},
  {"pt": "guardar", "en": "to keep/save", "type": "verb", "rank": 77},
  {"pt": "mostrar", "en": "to show", "type": "verb", "rank": 78},
  {"pt": "explicar", "en": "to explain", "type": "verb", "rank": 79},
  {"pt": "perguntar", "en": "to ask", "type": "verb", "rank": 80},
  {"pt": "responder", "en": "to answer", "type": "verb", "rank": 81},
  {"pt": "concordar", "en": "to agree", "type": "verb", "rank": 82},
  {"pt": "discordar", "en": "to disagree", "type": "verb", "rank": 83},
  {"pt": "aceitar", "en": "to accept", "type": "verb", "rank": 84},
  {"pt": "recusar", "en": "to refuse", "type": "verb", "rank": 85},
  {"pt": "permitir", "en": "to allow", "type": "verb", "rank": 86},
  {"pt": "proibir", "en": "to forbid", "type": "verb", "rank": 87},
  {"pt": "decidir", "en": "to decide", "type": "verb", "rank": 88},
  {"pt": "escolher", "en": "to choose", "type": "verb", "rank": 89},
  {"pt": "preferir", "en": "to prefer", "type": "verb", "rank": 90},
  {"pt": "oferecer", "en": "to offer", "type": "verb", "rank": 91},
  {"pt": "receber", "en": "to receive", "type": "verb", "rank": 92},
  {"pt": "enviar", "en": "to send", "type": "verb", "rank": 93},
  {"pt": "entregar", "en": "to deliver", "type": "verb", "rank": 94},
  {"pt": "convidar", "en": "to invite", "type": "verb", "rank": 95},
  {"pt": "visitar", "en": "to visit", "type": "verb", "rank": 96},
  {"pt": "viajar", "en": "to travel", "type": "verb", "rank": 97},
  {"pt": "voltar", "en": "to return", "type": "verb", "rank": 98},
  {"pt": "cair", "en": "to fall", "type": "verb", "rank": 99},
  {"pt": "subir", "en": "to go up", "type": "verb", "rank": 100},
  {"pt": "descer", "en": "to go down", "type": "verb", "rank": 101},
  {"pt": "quebrar", "en": "to break", "type": "verb", "rank": 102},
  {"pt": "consertar", "en": "to fix", "type": "verb", "rank": 103},
  {"pt": "limpar", "en": "to clean", "type": "verb", "rank": 104},
  {"pt": "lavar", "en": "to wash", "type": "verb", "rank": 105},
  {"pt": "cozinhar", "en": "to cook", "type": "verb", "rank": 106},
  {"pt": "cortar", "en": "to cut", "type": "verb", "rank": 107},
  {"pt": "colocar", "en": "to put/place", "type": "verb", "rank": 108},
  {"pt": "tirar", "en": "to remove/take off", "type": "verb", "rank": 109},
  {"pt": "segurar", "en": "to hold", "type": "verb", "rank": 110},
  {"pt": "empurrar", "en": "to push", "type": "verb", "rank": 111},
  {"pt": "puxar", "en": "to pull", "type": "verb", "rank": 112},
  {"pt": "bater", "en": "to hit/knock", "type": "verb", "rank": 113},
  {"pt": "machucar", "en": "to hurt", "type": "verb", "rank": 114},
  {"pt": "doer", "en": "to hurt/ache", "type": "verb", "rank": 115},
  {"pt": "curar", "en": "to heal/cure", "type": "verb", "rank": 116},
  {"pt": "cuidar", "en": "to take care", "type": "verb", "rank": 117},
  {"pt": "proteger", "en": "to protect", "type": "verb", "rank": 118},
  {"pt": "salvar", "en": "to save", "type": "verb", "rank": 119},
  {"pt": "lutar", "en": "to fight", "type": "verb", "rank": 120},
  {"pt": "vencer", "en": "to win/defeat", "type": "verb", "rank": 121},
  {"pt": "casar", "en": "to marry", "type": "verb", "rank": 122},
  {"pt": "namorar", "en": "to date", "type": "verb", "rank": 123},
  {"pt": "beijar", "en": "to kiss", "type": "verb", "rank": 124},
  {"pt": "abraçar", "en": "to hug", "type": "verb", "rank": 125},
  {"pt": "sorri", "en": "to smile", "type": "verb", "rank": 126},
  {"pt": "chorar", "en": "to cry", "type": "verb", "rank": 127},
  {"pt": "rir", "en": "to laugh", "type": "verb", "rank": 128},
  {"pt": "gritar", "en": "to scream", "type": "verb", "rank": 129},
  {"pt": "sussurrar", "en": "to whisper", "type": "verb", "rank": 130},
  {"pt": "acordar", "en": "to wake up", "type": "verb", "rank": 131},
  {"pt": "descansar", "en": "to rest", "type": "verb", "rank": 132},
  {"pt": "relaxar", "en": "to relax", "type": "verb", "rank": 133},
  {"pt": "aproveitar", "en": "to enjoy", "type": "verb", "rank": 134},
  {"pt": "divertir", "en": "to have fun", "type": "verb", "rank": 135},
  {"pt": "celebrar", "en": "to celebrate", "type": "verb", "rank": 136},
  {"pt": "comemorar", "en": "to commemorate", "type": "verb", "rank": 137},
  {"pt": "agradecer", "en": "to thank", "type": "verb", "rank": 138},
  {"pt": "desculpar", "en": "to apologize", "type": "verb", "rank": 139},
  {"pt": "perdoar", "en": "to forgive", "type": "verb", "rank": 140},
  {"pt": "confiar", "en": "to trust", "type": "verb", "rank": 141},
  {"pt": "acreditar", "en": "to believe", "type": "verb", "rank": 142},
  {"pt": "duvidar", "en": "to doubt", "type": "verb", "rank": 143},
  {"pt": "imaginar", "en": "to imagine", "type": "verb", "rank": 144},
  {"pt": "sonhar", "en": "to dream", "type": "verb", "rank": 145},
  {"pt": "desejar", "en": "to wish/desire", "type": "verb", "rank": 146},
  {"pt": "importar", "en": "to matter", "type": "verb", "rank": 147},
  {"pt": "interessar", "en": "to interest", "type": "verb", "rank": 148},
  {"pt": "preocupar", "en": "to worry", "type": "verb", "rank": 149},
  {"pt": "assustar", "en": "to scare", "type": "verb", "rank": 150},
  {"pt": "surpreender", "en": "to surprise", "type": "verb", "rank": 151},
  {"pt": "coisa", "en": "thing", "type": "noun", "rank": 152},
  {"pt": "casa", "en": "house/home", "type": "noun", "rank": 153},
  {"pt": "tempo", "en": "time/weather", "type": "noun", "rank": 154},
  {"pt": "dia", "en": "day", "type": "noun", "rank": 155},
  {"pt": "ano", "en": "year", "type": "noun", "rank": 156},
  {"pt": "vez", "en": "time/instance", "type": "noun", "rank": 157},
  {"pt": "homem", "en": "man", "type": "noun", "rank": 158},
  {"pt": "mulher", "en": "woman", "type": "noun", "rank": 159},
  {"pt": "mão", "en": "hand", "type": "noun", "rank": 160},
  {"pt": "palavra", "en": "word", "type": "noun", "rank": 161},
  {"pt": "filho", "en": "son/child", "type": "noun", "rank": 162},
  {"pt": "noite", "en": "night", "type": "noun", "rank": 163},
  {"pt": "amigo", "en": "friend", "type": "noun", "rank": 164},
  {"pt": "rua", "en": "street", "type": "noun", "rank": 165},
  {"pt": "vida", "en": "life", "type": "noun", "rank": 166},
  {"pt": "pessoa", "en": "person", "type": "noun", "rank": 167},
  {"pt": "menino", "en": "boy", "type": "noun", "rank": 168},
  {"pt": "menina", "en": "girl", "type": "noun", "rank": 169},
  {"pt": "senhor", "en": "sir/mister", "type": "noun", "rank": 170},
  {"pt": "senhora", "en": "ma'am/madam", "type": "noun", "rank": 171},
  {"pt": "trabalho", "en": "work/job", "type": "noun", "rank": 172},
  {"pt": "parte", "en": "part", "type": "noun", "rank": 173},
  {"pt": "lugar", "en": "place", "type": "noun", "rank": 174},
  {"pt": "cabeça", "en": "head", "type": "noun", "rank": 175},
  {"pt": "família", "en": "family", "type": "noun", "rank": 176},
  {"pt": "gente", "en": "people", "type": "noun", "rank": 177},
  {"pt": "frente", "en": "front", "type": "noun", "rank": 178},
  {"pt": "lado", "en": "side", "type": "noun", "rank": 179},
  {"pt": "caminho", "en": "way/path", "type": "noun", "rank": 180},
  {"pt": "minuto", "en": "minute", "type": "noun", "rank": 181},
  {"pt": "cidade", "en": "city", "type": "noun", "rank": 182},
  {"pt": "tarde", "en": "afternoon", "type": "noun", "rank": 183},
  {"pt": "momento", "en": "moment", "type": "noun", "rank": 184},
  {"pt": "medo", "en": "fear", "type": "noun", "rank": 185},
  {"pt": "caso", "en": "case", "type": "noun", "rank": 186},
  {"pt": "hora", "en": "hour/time", "type": "noun", "rank": 187},
  {"pt": "porta", "en": "door", "type": "noun", "rank": 188},
  {"pt": "irmão", "en": "brother", "type": "noun", "rank": 189},
  {"pt": "jeito", "en": "way/manner", "type": "noun", "rank": 190},
  {"pt": "semana", "en": "week", "type": "noun", "rank": 191},
  {"pt": "garoto", "en": "boy/kid", "type": "noun", "rank": 192},
  {"pt": "garota", "en": "girl/kid", "type": "noun", "rank": 193},
  {"pt": "papai", "en": "dad/daddy", "type": "noun", "rank": 194},
  {"pt": "mamãe", "en": "mom/mommy", "type": "noun", "rank": 195},
  {"pt": "morte", "en": "death", "type": "noun", "rank": 196},
  {"pt": "polícia", "en": "police", "type": "noun", "rank": 197},
  {"pt": "arma", "en": "weapon/gun", "type": "noun", "rank": 198},
  {"pt": "manhã", "en": "morning", "type": "noun", "rank": 199},
  {"pt": "quarto", "en": "bedroom/room", "type": "noun", "rank": 200},
  {"pt": "criança", "en": "child", "type": "noun", "rank": 201},
  {"pt": "forma", "en": "form/way", "type": "noun", "rank": 202},
  {"pt": "conta", "en": "account/bill", "type": "noun", "rank": 203},
  {"pt": "chefe", "en": "boss", "type": "noun", "rank": 204},
  {"pt": "olho", "en": "eye", "type": "noun", "rank": 205},
  {"pt": "filha", "en": "daughter", "type": "noun", "rank": 206},
  {"pt": "esposa", "en": "wife", "type": "noun", "rank": 207},
  {"pt": "marido", "en": "husband", "type": "noun", "rank": 208},
  {"pt": "problema", "en": "problem", "type": "noun", "rank": 209},
  {"pt": "jogo", "en": "game", "type": "noun", "rank": 210},
  {"pt": "guerra", "en": "war", "type": "noun", "rank": 211},
  {"pt": "água", "en": "water", "type": "noun", "rank": 212},
  {"pt": "boca", "en": "mouth", "type": "noun", "rank": 213},
  {"pt": "coração", "en": "heart", "type": "noun", "rank": 214},
  {"pt": "escola", "en": "school", "type": "noun", "rank": 215},
  {"pt": "corpo", "en": "body", "type": "noun", "rank": 216},
  {"pt": "licença", "en": "license/permission", "type": "noun", "rank": 217},
  {"pt": "causa", "en": "cause", "type": "noun", "rank": 218},
  {"pt": "terra", "en": "earth/land", "type": "noun", "rank": 219},
  {"pt": "dinheiro", "en": "money", "type": "noun", "rank": 220},
  {"pt": "nome", "en": "name", "type": "noun", "rank": 221},
  {"pt": "mundo", "en": "world", "type": "noun", "rank": 222},
  {"pt": "novo", "en": "new", "type": "adjective", "rank": 223},
  {"pt": "grande", "en": "big/large", "type": "adjective", "rank": 224},
  {"pt": "pequeno", "en": "small", "type": "adjective", "rank": 225},
  {"pt": "bom", "en": "good", "type": "adjective", "rank": 226},
  {"pt": "ruim", "en": "bad", "type": "adjective", "rank": 227},
  {"pt": "melhor", "en": "better/best", "type": "adjective", "rank": 228},
  {"pt": "pior", "en": "worse/worst", "type": "adjective", "rank": 229},
  {"pt": "certo", "en": "right/correct", "type": "adjective", "rank": 230},
  {"pt": "errado", "en": "wrong", "type": "adjective", "rank": 231},
  {"pt": "velho", "en": "old", "type": "adjective", "rank": 232},
  {"pt": "difícil", "en": "difficult/hard", "type": "adjective", "rank": 233},
  {"pt": "fácil", "en": "easy", "type": "adjective", "rank": 234},
  {"pt": "bonito", "en": "beautiful/handsome", "type": "adjective", "rank": 235},
  {"pt": "feio", "en": "ugly", "type": "adjective", "rank": 236},
  {"pt": "forte", "en": "strong", "type": "adjective", "rank": 237},
  {"pt": "fraco", "en": "weak", "type": "adjective", "rank": 238},
  {"pt": "feliz", "en": "happy", "type": "adjective", "rank": 239},
  {"pt": "triste", "en": "sad", "type": "adjective", "rank": 240},
  {"pt": "diferente", "en": "different", "type": "adjective", "rank": 241},
  {"pt": "importante", "en": "important", "type": "adjective", "rank": 242},
  {"pt": "mesmo", "en": "same", "type": "adjective", "rank": 243},
  {"pt": "único", "en": "only/unique", "type": "adjective", "rank": 244},
  {"pt": "outro", "en": "other", "type": "adjective", "rank": 245},
  {"pt": "todo", "en": "all/every", "type": "adjective", "rank": 246},
  {"pt": "algum", "en": "some/any", "type": "adjective", "rank": 247},
  {"pt": "nenhum", "en": "none/no", "type": "adjective", "rank": 248},
  {"pt": "próprio", "en": "own", "type": "adjective", "rank": 249},
  {"pt": "primeiro", "en": "first", "type": "adjective", "rank": 250},
  {"pt": "último", "en": "last", "type": "adjective", "rank": 251},
  {"pt": "segundo", "en": "second", "type": "adjective", "rank": 252},
  {"pt": "terceiro", "en": "third", "type": "adjective", "rank": 253},
  {"pt": "jovem", "en": "young", "type": "adjective", "rank": 254},
  {"pt": "alto", "en": "tall/high", "type": "adjective", "rank": 255},
  {"pt": "baixo", "en": "short/low", "type": "adjective", "rank": 256},
  {"pt": "lindo", "en": "beautiful", "type": "adjective", "rank": 257},
  {"pt": "maravilhoso", "en": "wonderful", "type": "adjective", "rank": 258},
  {"pt": "incrível", "en": "incredible", "type": "adjective", "rank": 259},
  {"pt": "horrível", "en": "horrible", "type": "adjective", "rank": 260},
  {"pt": "terrível", "en": "terrible", "type": "adjective", "rank": 261},
  {"pt": "perfeito", "en": "perfect", "type": "adjective", "rank": 262},
  {"pt": "completo", "en": "complete", "type": "adjective", "rank": 263},
  {"pt": "cheio", "en": "full", "type": "adjective", "rank": 264},
  {"pt": "vazio", "en": "empty", "type": "adjective", "rank": 265},
  {"pt": "aberto", "en": "open", "type": "adjective", "rank": 266},
  {"pt": "fechado", "en": "closed", "type": "adjective", "rank": 267},
  {"pt": "quebrado", "en": "broken", "type": "adjective", "rank": 268},
  {"pt": "novo", "en": "new", "type": "adjective", "rank": 269},
  {"pt": "usado", "en": "used", "type": "adjective", "rank": 270},
  {"pt": "caro", "en": "expensive", "type": "adjective", "rank": 271},
  {"pt": "barato", "en": "cheap", "type": "adjective", "rank": 272},
  {"pt": "rico", "en": "rich", "type": "adjective", "rank": 273},
  {"pt": "pobre", "en": "poor", "type": "adjective", "rank": 274},
  {"pt": "saudável", "en": "healthy", "type": "adjective", "rank": 275},
  {"pt": "doente", "en": "sick", "type": "adjective", "rank": 276},
  {"pt": "cansado", "en": "tired", "type": "adjective", "rank": 277},
  {"pt": "ocupado", "en": "busy", "type": "adjective", "rank": 278},
  {"pt": "livre", "en": "free", "type": "adjective", "rank": 279},
  {"pt": "preso", "en": "arrested/trapped", "type": "adjective", "rank": 280},
  {"pt": "seguro", "en": "safe/secure", "type": "adjective", "rank": 281},
  {"pt": "perigoso", "en": "dangerous", "type": "adjective", "rank": 282},
  {"pt": "calmo", "en": "calm", "type": "adjective", "rank": 283},
  {"pt": "nervoso", "en": "nervous", "type": "adjective", "rank": 284},
  {"pt": "tranquilo", "en": "calm/relaxed", "type": "adjective", "rank": 285},
  {"pt": "agitado", "en": "agitated/busy", "type": "adjective", "rank": 286},
  {"pt": "silencioso", "en": "quiet/silent", "type": "adjective", "rank": 287},
  {"pt": "barulhento", "en": "noisy", "type": "adjective", "rank": 288},
  {"pt": "claro", "en": "clear/light", "type": "adjective", "rank": 289},
  {"pt": "escuro", "en": "dark", "type": "adjective", "rank": 290},
  {"pt": "quente", "en": "hot", "type": "adjective", "rank": 291},
  {"pt": "frio", "en": "cold", "type": "adjective", "rank": 292},
  {"pt": "morno", "en": "warm", "type": "adjective", "rank": 293},
  {"pt": "gelado", "en": "frozen/ice cold", "type": "adjective", "rank": 294},
  {"pt": "seco", "en": "dry", "type": "adjective", "rank": 295},
  {"pt": "molhado", "en": "wet", "type": "adjective", "rank": 296},
  {"pt": "limpo", "en": "clean", "type": "adjective", "rank": 297},
  {"pt": "sujo", "en": "dirty", "type": "adjective", "rank": 298},
  {"pt": "doce", "en": "sweet", "type": "adjective", "rank": 299},
  {"pt": "salgado", "en": "salty", "type": "adjective", "rank": 300},
  {"pt": "azedo", "en": "sour", "type": "adjective", "rank": 301},
  {"pt": "amargo", "en": "bitter", "type": "adjective", "rank": 302},
  {"pt": "delicioso", "en": "delicious", "type": "adjective", "rank": 303},
  {"pt": "gostoso", "en": "tasty", "type": "adjective", "rank": 304},
  {"pt": "sem graça", "en": "bland/boring", "type": "adjective", "rank": 305},
  {"pt": "engraçado", "en": "funny", "type": "adjective", "rank": 306},
  {"pt": "sério", "en": "serious", "type": "adjective", "rank": 307},
  {"pt": "gentil", "en": "kind", "type": "adjective", "rank": 308},
  {"pt": "mau", "en": "bad/evil", "type": "adjective", "rank": 309},
  {"pt": "bom", "en": "good/kind", "type": "adjective", "rank": 310},
  {"pt": "inteligente", "en": "intelligent", "type": "adjective", "rank": 311},
  {"pt": "burro", "en": "stupid", "type": "adjective", "rank": 312},
  {"pt": "sábio", "en": "wise", "type": "adjective", "rank": 313},
  {"pt": "curioso", "en": "curious", "type": "adjective", "rank": 314},
  {"pt": "tímido", "en": "shy", "type": "adjective", "rank": 315},
  {"pt": "extrovertido", "en": "extroverted", "type": "adjective", "rank": 316},
  {"pt": "simpático", "en": "nice/likeable", "type": "adjective", "rank": 317},
  {"pt": "antipático", "en": "unpleasant", "type": "adjective", "rank": 318},
  {"pt": "generoso", "en": "generous", "type": "adjective", "rank": 319},
  {"pt": "egoísta", "en": "selfish", "type": "adjective", "rank": 320},
  {"pt": "paciente", "en": "patient", "type": "adjective", "rank": 321},
  {"pt": "impaciente", "en": "impatient", "type": "adjective", "rank": 322},
  {"pt": "honesto", "en": "honest", "type": "adjective", "rank": 323},
  {"pt": "desonesto", "en": "dishonest", "type": "adjective", "rank": 324},
  {"pt": "leal", "en": "loyal", "type": "adjective", "rank": 325},
  {"pt": "traidor", "en": "traitorous", "type": "adjective", "rank": 326},
  {"pt": "corajoso", "en": "brave", "type": "adjective", "rank": 327},
  {"pt": "covarde", "en": "cowardly", "type": "adjective", "rank": 328},
  {"pt": "otimista", "en": "optimistic", "type": "adjective", "rank": 329},
  {"pt": "pessimista", "en": "pessimistic", "type": "adjective", "rank": 330},
  {"pt": "realista", "en": "realistic", "type": "adjective", "rank": 331},
  {"pt": "romântico", "en": "romantic", "type": "adjective", "rank": 332},
  {"pt": "prático", "en": "practical", "type": "adjective", "rank": 333},
  {"pt": "útil", "en": "useful", "type": "adjective", "rank": 334},
  {"pt": "inútil", "en": "useless", "type": "adjective", "rank": 335},
  {"pt": "necessário", "en": "necessary", "type": "adjective", "rank": 336},
  {"pt": "possível", "en": "possible", "type": "adjective", "rank": 337},
  {"pt": "impossível", "en": "impossible", "type": "adjective", "rank": 338},
  {"pt": "provável", "en": "probable", "type": "adjective", "rank": 339},
  {"pt": "improvável", "en": "improbable", "type": "adjective", "rank": 340},
  {"pt": "comum", "en": "common", "type": "adjective", "rank": 341},
  {"pt": "raro", "en": "rare", "type": "adjective", "rank": 342},
  {"pt": "normal", "en": "normal", "type": "adjective", "rank": 343},
  {"pt": "anormal", "en": "abnormal", "type": "adjective", "rank": 344},
  {"pt": "natural", "en": "natural", "type": "adjective", "rank": 345},
  {"pt": "artificial", "en": "artificial", "type": "adjective", "rank": 346},
  {"pt": "verdadeiro", "en": "true/real", "type": "adjective", "rank": 347},
  {"pt": "falso", "en": "false/fake", "type": "adjective", "rank": 348},
  {"pt": "real", "en": "real", "type": "adjective", "rank": 349},
  {"pt": "imaginário", "en": "imaginary", "type": "adjective", "rank": 350},
  {"pt": "não", "en": "no/not", "type": "adverb", "rank": 351},
  {"pt": "sim", "en": "yes", "type": "adverb", "rank": 352},
  {"pt": "talvez", "en": "maybe", "type": "adverb", "rank": 353},
  {"pt": "muito", "en": "very/many", "type": "adverb", "rank": 354},
  {"pt": "pouco", "en": "a little", "type": "adverb", "rank": 355},
  {"pt": "também", "en": "also/too", "type": "adverb", "rank": 356},
  {"pt": "perto", "en": "near/close", "type": "adverb", "rank": 357},
  {"pt": "longe", "en": "far", "type": "adverb", "rank": 358},
  {"pt": "sempre", "en": "always", "type": "adverb", "rank": 359},
  {"pt": "nunca", "en": "never", "type": "adverb", "rank": 360},
  {"pt": "agora", "en": "now", "type": "adverb", "rank": 361},
  {"pt": "antes", "en": "before", "type": "adverb", "rank": 362},
  {"pt": "depois", "en": "after/later", "type": "adverb", "rank": 363},
  {"pt": "aqui", "en": "here", "type": "adverb", "rank": 364},
  {"pt": "lá", "en": "there", "type": "adverb", "rank": 365},
  {"pt": "apenas", "en": "only/just", "type": "adverb", "rank": 366},
  {"pt": "mais", "en": "more", "type": "adverb", "rank": 367},
  {"pt": "menos", "en": "less", "type": "adverb", "rank": 368},
  {"pt": "cedo", "en": "early", "type": "adverb", "rank": 369},
  {"pt": "tarde", "en": "late", "type": "adverb", "rank": 370},
  {"pt": "bem", "en": "well", "type": "adverb", "rank": 371},
  {"pt": "mal", "en": "badly", "type": "adverb", "rank": 372},
  {"pt": "rápido", "en": "fast/quickly", "type": "adverb", "rank": 373},
  {"pt": "devagar", "en": "slowly", "type": "adverb", "rank": 374},
  {"pt": "junto", "en": "together", "type": "adverb", "rank": 375},
  {"pt": "sozinho", "en": "alone", "type": "adverb", "rank": 376},
  {"pt": "quase", "en": "almost", "type": "adverb", "rank": 377},
  {"pt": "totalmente", "en": "totally", "type": "adverb", "rank": 378},
  {"pt": "completamente", "en": "completely", "type": "adverb", "rank": 379},
  {"pt": "parcialmente", "en": "partially", "type": "adverb", "rank": 380},
  {"pt": "realmente", "en": "really", "type": "adverb", "rank": 381},
  {"pt": "verdadeiramente", "en": "truly", "type": "adverb", "rank": 382},
  {"pt": "provavelmente", "en": "probably", "type": "adverb", "rank": 383},
  {"pt": "certamente", "en": "certainly", "type": "adverb", "rank": 384},
  {"pt": "obviamente", "en": "obviously", "type": "adverb", "rank": 385},
  {"pt": "claramente", "en": "clearly", "type": "adverb", "rank": 386},
  {"pt": "facilmente", "en": "easily", "type": "adverb", "rank": 387},
  {"pt": "dificilmente", "en": "hardly", "type": "adverb", "rank": 388},
  {"pt": "finalmente", "en": "finally", "type": "adverb", "rank": 389},
  {"pt": "imediatamente", "en": "immediately", "type": "adverb", "rank": 390},
  {"pt": "rapidamente", "en": "quickly", "type": "adverb", "rank": 391},
  {"pt": "lentamente", "en": "slowly", "type": "adverb", "rank": 392},
  {"pt": "calmamente", "en": "calmly", "type": "adverb", "rank": 393},
  {"pt": "nervosamente", "en": "nervously", "type": "adverb", "rank": 394},
  {"pt": "felizmente", "en": "happily/fortunately", "type": "adverb", "rank": 395},
  {"pt": "infelizmente", "en": "unfortunately", "type": "adverb", "rank": 396},
  {"pt": "naturalmente", "en": "naturally", "type": "adverb", "rank": 397},
  {"pt": "normalmente", "en": "normally", "type": "adverb", "rank": 398},
  {"pt": "geralmente", "en": "generally", "type": "adverb", "rank": 399},
  {"pt": "especialmente", "en": "especially", "type": "adverb", "rank": 400}
];

// Combine all words
const ALL_WORDS = [...FUNCTION_WORDS, ...CONTENT_WORDS];

// Generate example sentences for content words (they don't have examples in the source data)
function generateExample(word) {
    const type = word.type;
    const pt = word.pt;
    const en = word.en;
    
    // Simple template-based examples
    const templates = {
        verb: {
            pt: `Eu vou ${pt} amanhã.`,
            en: `I will ${en.replace('to ', '')} tomorrow.`
        },
        noun: {
            pt: `A ${pt} está aqui.`,
            en: `The ${en} is here.`
        },
        adjective: {
            pt: `Isso é muito ${pt}.`,
            en: `This is very ${en}.`
        },
        adverb: {
            pt: `Ele fez ${pt}.`,
            en: `He did it ${en}.`
        }
    };
    
    return templates[type] || { pt: `${pt}`, en: `${en}` };
}

// Normalize word data - add examples where missing
function normalizeWord(word, index) {
    return {
        id: index,
        pt: word.pt,
        en: word.en,
        type: word.type,
        example_pt: word.example_pt || generateExample(word).pt,
        example_en: word.example_en || generateExample(word).en,
        rank: word.rank || index
    };
}

// Create normalized word list
const WORDS = ALL_WORDS.map((word, index) => normalizeWord(word, index));

// Filter helpers
const WORD_TYPES = {
    all: WORDS,
    function: FUNCTION_WORDS.map((w, i) => normalizeWord(w, i)),
    verb: WORDS.filter(w => w.type === 'verb'),
    noun: WORDS.filter(w => w.type === 'noun'),
    adjective: WORDS.filter(w => w.type === 'adjective'),
    adverb: WORDS.filter(w => w.type === 'adverb'),
    pronoun: WORDS.filter(w => w.type === 'pronoun'),
    article: WORDS.filter(w => w.type === 'article'),
    preposition: WORDS.filter(w => w.type === 'preposition'),
    conjunction: WORDS.filter(w => w.type === 'conjunction')
};

// Export for use in app
window.WORDS = WORDS;
window.WORD_TYPES = WORD_TYPES;
window.FUNCTION_WORDS = FUNCTION_WORDS;
window.CONTENT_WORDS = CONTENT_WORDS;
